
INSERT INTO TB_USUARIOS (NOME, EMAIL) VALUES ('ADILSON', 'A@A.COM');
INSERT INTO TB_USUARIOS (NOME, EMAIL) VALUES ('RENATO', 'R@A.COM');
INSERT INTO TB_USUARIOS (NOME, EMAIL) VALUES ('OSMAR', 'O@A.COM');


INSERT INTO TB_CIDADES (NOME_CIDADE) VALUES ('SAO PAULO');
INSERT INTO TB_CIDADES (NOME_CIDADE) VALUES ('RIO DE JANEIRO');
INSERT INTO TB_CIDADES (NOME_CIDADE) VALUES ('FLORIANOPOLIS');
INSERT INTO TB_CIDADES (NOME_CIDADE) VALUES ('SALVADOR');
INSERT INTO TB_CIDADES (NOME_CIDADE) VALUES ('VICOSA');
INSERT INTO TB_CIDADES (NOME_CIDADE) VALUES ('RIBEIRAO PRETO');
INSERT INTO TB_CIDADES (NOME_CIDADE) VALUES ('CAMPINAS');
INSERT INTO TB_CIDADES (NOME_CIDADE) VALUES ('JOINVILE');
INSERT INTO TB_CIDADES (NOME_CIDADE) VALUES ('SAO JOSE');


INSERT INTO TB_FILMES (NOME_FILME) VALUES ('ET');
INSERT INTO TB_FILMES (NOME_FILME) VALUES ('A CACADA');
INSERT INTO TB_FILMES (NOME_FILME) VALUES ('A HORA DO ESPANTO');
INSERT INTO TB_FILMES (NOME_FILME) VALUES ('RAMBO');
INSERT INTO TB_FILMES (NOME_FILME) VALUES ('PREDADOR');
INSERT INTO TB_FILMES (NOME_FILME) VALUES ('MISSAO IMPOSSIVEL');

INSERT INTO CIDADE_FILME (CIDADE_ID,FILME_ID) VALUES (1,1);
INSERT INTO CIDADE_FILME (CIDADE_ID,FILME_ID) VALUES (1,2);
INSERT INTO CIDADE_FILME (CIDADE_ID,FILME_ID) VALUES (1,3);
INSERT INTO CIDADE_FILME (CIDADE_ID,FILME_ID) VALUES (1,4);
INSERT INTO CIDADE_FILME (CIDADE_ID,FILME_ID) VALUES (1,5);

INSERT INTO CIDADE_FILME (CIDADE_ID,FILME_ID) VALUES (2,1);
INSERT INTO CIDADE_FILME (CIDADE_ID,FILME_ID) VALUES (2,2);
INSERT INTO CIDADE_FILME (CIDADE_ID,FILME_ID) VALUES (2,3);
INSERT INTO CIDADE_FILME (CIDADE_ID,FILME_ID) VALUES (2,4);
INSERT INTO CIDADE_FILME (CIDADE_ID,FILME_ID) VALUES (2,5);
INSERT INTO CIDADE_FILME (CIDADE_ID,FILME_ID) VALUES (2,6);

INSERT INTO CIDADE_FILME (CIDADE_ID,FILME_ID) VALUES (3,3);
INSERT INTO CIDADE_FILME (CIDADE_ID,FILME_ID) VALUES (3,4);
INSERT INTO CIDADE_FILME (CIDADE_ID,FILME_ID) VALUES (3,5);

INSERT INTO CIDADE_FILME (CIDADE_ID,FILME_ID) VALUES (4,5);
INSERT INTO CIDADE_FILME (CIDADE_ID,FILME_ID) VALUES (5,6);

INSERT INTO CIDADE_FILME (CIDADE_ID,FILME_ID) VALUES (5,1);
INSERT INTO CIDADE_FILME (CIDADE_ID,FILME_ID) VALUES (5,2);
INSERT INTO CIDADE_FILME (CIDADE_ID,FILME_ID) VALUES (6,3);
INSERT INTO CIDADE_FILME (CIDADE_ID,FILME_ID) VALUES (6,4);
INSERT INTO CIDADE_FILME (CIDADE_ID,FILME_ID) VALUES (7,5);

INSERT INTO CIDADE_FILME (CIDADE_ID,FILME_ID) VALUES (8,5);
INSERT INTO CIDADE_FILME (CIDADE_ID,FILME_ID) VALUES (8,6);

INSERT INTO CIDADE_FILME (CIDADE_ID,FILME_ID) VALUES (8,3);
INSERT INTO CIDADE_FILME (CIDADE_ID,FILME_ID) VALUES (9,4);
INSERT INTO CIDADE_FILME (CIDADE_ID,FILME_ID) VALUES (9,5);

INSERT INTO CIDADE_FILME (CIDADE_ID,FILME_ID) VALUES (9,5);
INSERT INTO CIDADE_FILME (CIDADE_ID,FILME_ID) VALUES (9,6);


INSERT INTO TB_CINEMAS (NOME_CINEMA) VALUES ('CINEMA 1');
INSERT INTO TB_CINEMAS (NOME_CINEMA) VALUES ('CINEMA 2');
INSERT INTO TB_CINEMAS (NOME_CINEMA) VALUES ('CINEMA 3');
INSERT INTO TB_CINEMAS (NOME_CINEMA) VALUES ('CINEMA 4');
INSERT INTO TB_CINEMAS (NOME_CINEMA) VALUES ('CINEMA 5');
INSERT INTO TB_CINEMAS (NOME_CINEMA) VALUES ('CINEMA 6');
INSERT INTO TB_CINEMAS (NOME_CINEMA) VALUES ('CINEMA 7');
INSERT INTO TB_CINEMAS (NOME_CINEMA) VALUES ('CINEMA 8');
INSERT INTO TB_CINEMAS (NOME_CINEMA) VALUES ('CINEMA 9');
INSERT INTO TB_CINEMAS (NOME_CINEMA) VALUES ('CINEMA 10');
INSERT INTO TB_CINEMAS (NOME_CINEMA) VALUES ('CINEMA 11');
INSERT INTO TB_CINEMAS (NOME_CINEMA) VALUES ('CINEMA 12');
INSERT INTO TB_CINEMAS (NOME_CINEMA) VALUES ('CINEMA 13');
INSERT INTO TB_CINEMAS (NOME_CINEMA) VALUES ('CINEMA 14');
INSERT INTO TB_CINEMAS (NOME_CINEMA) VALUES ('CINEMA 15');


INSERT INTO TB_HORARIO (HORARIO,PRECO) VALUES (TIMESTAMP WITH TIME ZONE '2021-01-01T12:00:00Z',20.00);

INSERT INTO TB_HORARIO (HORARIO,PRECO) VALUES (TIMESTAMP WITH TIME ZONE '2021-01-01T15:00:00Z',30.00);

INSERT INTO TB_HORARIO (HORARIO,PRECO) VALUES (TIMESTAMP WITH TIME ZONE '2021-01-01T21:00:00Z',35.00);


INSERT INTO TB_ACENTO (ACENTO_RESERVADO,NUMERO_CADEIRA) VALUES (false,1);
INSERT INTO TB_ACENTO (ACENTO_RESERVADO,NUMERO_CADEIRA) VALUES (false,2);
INSERT INTO TB_ACENTO (ACENTO_RESERVADO,NUMERO_CADEIRA) VALUES (false,3);
INSERT INTO TB_ACENTO (ACENTO_RESERVADO,NUMERO_CADEIRA) VALUES (false,4);
INSERT INTO TB_ACENTO (ACENTO_RESERVADO,NUMERO_CADEIRA) VALUES (false,5);
INSERT INTO TB_ACENTO (ACENTO_RESERVADO,NUMERO_CADEIRA) VALUES (false,6);
INSERT INTO TB_ACENTO (ACENTO_RESERVADO,NUMERO_CADEIRA) VALUES (false,7);
INSERT INTO TB_ACENTO (ACENTO_RESERVADO,NUMERO_CADEIRA) VALUES (false,8);
INSERT INTO TB_ACENTO (ACENTO_RESERVADO,NUMERO_CADEIRA) VALUES (false,9);
INSERT INTO TB_ACENTO (ACENTO_RESERVADO,NUMERO_CADEIRA) VALUES (false,10);
INSERT INTO TB_ACENTO (ACENTO_RESERVADO,NUMERO_CADEIRA) VALUES (false,11);
INSERT INTO TB_ACENTO (ACENTO_RESERVADO,NUMERO_CADEIRA) VALUES (false,12);
INSERT INTO TB_ACENTO (ACENTO_RESERVADO,NUMERO_CADEIRA) VALUES (false,13);
INSERT INTO TB_ACENTO (ACENTO_RESERVADO,NUMERO_CADEIRA) VALUES (false,14);
INSERT INTO TB_ACENTO (ACENTO_RESERVADO,NUMERO_CADEIRA) VALUES (false,15);
INSERT INTO TB_ACENTO (ACENTO_RESERVADO,NUMERO_CADEIRA) VALUES (false,16);
INSERT INTO TB_ACENTO (ACENTO_RESERVADO,NUMERO_CADEIRA) VALUES (false,17);
INSERT INTO TB_ACENTO (ACENTO_RESERVADO,NUMERO_CADEIRA) VALUES (false,18);
INSERT INTO TB_ACENTO (ACENTO_RESERVADO,NUMERO_CADEIRA) VALUES (false,19);
INSERT INTO TB_ACENTO (ACENTO_RESERVADO,NUMERO_CADEIRA) VALUES (false,20);



INSERT INTO FILME_CINEMA (FILME_ID,CINEMA_ID) VALUES (1,1);
INSERT INTO FILME_CINEMA (FILME_ID,CINEMA_ID) VALUES (2,1);
INSERT INTO FILME_CINEMA (FILME_ID,CINEMA_ID) VALUES (3,1);
INSERT INTO FILME_CINEMA (FILME_ID,CINEMA_ID) VALUES (4,1);
INSERT INTO FILME_CINEMA (FILME_ID,CINEMA_ID) VALUES (4,1);
INSERT INTO FILME_CINEMA (FILME_ID,CINEMA_ID) VALUES (6,1);

INSERT INTO FILME_CINEMA (FILME_ID,CINEMA_ID) VALUES (1,2);
INSERT INTO FILME_CINEMA (FILME_ID,CINEMA_ID) VALUES (2,2);
INSERT INTO FILME_CINEMA (FILME_ID,CINEMA_ID) VALUES (3,2);
INSERT INTO FILME_CINEMA (FILME_ID,CINEMA_ID) VALUES (4,2);
INSERT INTO FILME_CINEMA (FILME_ID,CINEMA_ID) VALUES (4,2);
INSERT INTO FILME_CINEMA (FILME_ID,CINEMA_ID) VALUES (6,2);

INSERT INTO FILME_CINEMA (FILME_ID,CINEMA_ID) VALUES (1,3);
INSERT INTO FILME_CINEMA (FILME_ID,CINEMA_ID) VALUES (2,3);
INSERT INTO FILME_CINEMA (FILME_ID,CINEMA_ID) VALUES (3,3);
INSERT INTO FILME_CINEMA (FILME_ID,CINEMA_ID) VALUES (4,3);
INSERT INTO FILME_CINEMA (FILME_ID,CINEMA_ID) VALUES (4,3);
INSERT INTO FILME_CINEMA (FILME_ID,CINEMA_ID) VALUES (6,3);

INSERT INTO FILME_CINEMA (FILME_ID,CINEMA_ID) VALUES (1,4);
INSERT INTO FILME_CINEMA (FILME_ID,CINEMA_ID) VALUES (2,4);
INSERT INTO FILME_CINEMA (FILME_ID,CINEMA_ID) VALUES (3,4);
INSERT INTO FILME_CINEMA (FILME_ID,CINEMA_ID) VALUES (4,4);
INSERT INTO FILME_CINEMA (FILME_ID,CINEMA_ID) VALUES (4,4);
INSERT INTO FILME_CINEMA (FILME_ID,CINEMA_ID) VALUES (6,4);

INSERT INTO FILME_CINEMA (FILME_ID,CINEMA_ID) VALUES (1,5);
INSERT INTO FILME_CINEMA (FILME_ID,CINEMA_ID) VALUES (2,5);
INSERT INTO FILME_CINEMA (FILME_ID,CINEMA_ID) VALUES (3,5);
INSERT INTO FILME_CINEMA (FILME_ID,CINEMA_ID) VALUES (4,5);
INSERT INTO FILME_CINEMA (FILME_ID,CINEMA_ID) VALUES (4,5);
INSERT INTO FILME_CINEMA (FILME_ID,CINEMA_ID) VALUES (6,5);

INSERT INTO FILME_CINEMA (FILME_ID,CINEMA_ID) VALUES (1,6);
INSERT INTO FILME_CINEMA (FILME_ID,CINEMA_ID) VALUES (2,6);
INSERT INTO FILME_CINEMA (FILME_ID,CINEMA_ID) VALUES (3,6);
INSERT INTO FILME_CINEMA (FILME_ID,CINEMA_ID) VALUES (4,6);
INSERT INTO FILME_CINEMA (FILME_ID,CINEMA_ID) VALUES (4,6);
INSERT INTO FILME_CINEMA (FILME_ID,CINEMA_ID) VALUES (6,6);

INSERT INTO FILME_CINEMA (FILME_ID,CINEMA_ID) VALUES (1,7);
INSERT INTO FILME_CINEMA (FILME_ID,CINEMA_ID) VALUES (2,7);
INSERT INTO FILME_CINEMA (FILME_ID,CINEMA_ID) VALUES (3,7);
INSERT INTO FILME_CINEMA (FILME_ID,CINEMA_ID) VALUES (4,7);
INSERT INTO FILME_CINEMA (FILME_ID,CINEMA_ID) VALUES (4,7);
INSERT INTO FILME_CINEMA (FILME_ID,CINEMA_ID) VALUES (6,7);

INSERT INTO FILME_CINEMA (FILME_ID,CINEMA_ID) VALUES (1,8);
INSERT INTO FILME_CINEMA (FILME_ID,CINEMA_ID) VALUES (2,8);
INSERT INTO FILME_CINEMA (FILME_ID,CINEMA_ID) VALUES (3,8);
INSERT INTO FILME_CINEMA (FILME_ID,CINEMA_ID) VALUES (4,8);
INSERT INTO FILME_CINEMA (FILME_ID,CINEMA_ID) VALUES (4,8);
INSERT INTO FILME_CINEMA (FILME_ID,CINEMA_ID) VALUES (6,8);

INSERT INTO FILME_CINEMA (FILME_ID,CINEMA_ID) VALUES (1,9);
INSERT INTO FILME_CINEMA (FILME_ID,CINEMA_ID) VALUES (2,9);
INSERT INTO FILME_CINEMA (FILME_ID,CINEMA_ID) VALUES (3,9);
INSERT INTO FILME_CINEMA (FILME_ID,CINEMA_ID) VALUES (4,9);
INSERT INTO FILME_CINEMA (FILME_ID,CINEMA_ID) VALUES (4,9);
INSERT INTO FILME_CINEMA (FILME_ID,CINEMA_ID) VALUES (6,9);

INSERT INTO FILME_CINEMA (FILME_ID,CINEMA_ID) VALUES (1,10);
INSERT INTO FILME_CINEMA (FILME_ID,CINEMA_ID) VALUES (2,10);
INSERT INTO FILME_CINEMA (FILME_ID,CINEMA_ID) VALUES (3,10);
INSERT INTO FILME_CINEMA (FILME_ID,CINEMA_ID) VALUES (4,10);
INSERT INTO FILME_CINEMA (FILME_ID,CINEMA_ID) VALUES (4,10);
INSERT INTO FILME_CINEMA (FILME_ID,CINEMA_ID) VALUES (6,10);

INSERT INTO FILME_CINEMA (FILME_ID,CINEMA_ID) VALUES (1,11);
INSERT INTO FILME_CINEMA (FILME_ID,CINEMA_ID) VALUES (2,11);
INSERT INTO FILME_CINEMA (FILME_ID,CINEMA_ID) VALUES (3,11);
INSERT INTO FILME_CINEMA (FILME_ID,CINEMA_ID) VALUES (4,11);
INSERT INTO FILME_CINEMA (FILME_ID,CINEMA_ID) VALUES (4,11);
INSERT INTO FILME_CINEMA (FILME_ID,CINEMA_ID) VALUES (6,11);

INSERT INTO FILME_CINEMA (FILME_ID,CINEMA_ID) VALUES (1,12);
INSERT INTO FILME_CINEMA (FILME_ID,CINEMA_ID) VALUES (2,12);
INSERT INTO FILME_CINEMA (FILME_ID,CINEMA_ID) VALUES (3,12);
INSERT INTO FILME_CINEMA (FILME_ID,CINEMA_ID) VALUES (4,12);
INSERT INTO FILME_CINEMA (FILME_ID,CINEMA_ID) VALUES (4,12);
INSERT INTO FILME_CINEMA (FILME_ID,CINEMA_ID) VALUES (6,12);

INSERT INTO FILME_CINEMA (FILME_ID,CINEMA_ID) VALUES (1,13);
INSERT INTO FILME_CINEMA (FILME_ID,CINEMA_ID) VALUES (2,13);
INSERT INTO FILME_CINEMA (FILME_ID,CINEMA_ID) VALUES (3,13);
INSERT INTO FILME_CINEMA (FILME_ID,CINEMA_ID) VALUES (4,13);
INSERT INTO FILME_CINEMA (FILME_ID,CINEMA_ID) VALUES (4,13);
INSERT INTO FILME_CINEMA (FILME_ID,CINEMA_ID) VALUES (6,13);

INSERT INTO FILME_CINEMA (FILME_ID,CINEMA_ID) VALUES (1,14);
INSERT INTO FILME_CINEMA (FILME_ID,CINEMA_ID) VALUES (2,14);
INSERT INTO FILME_CINEMA (FILME_ID,CINEMA_ID) VALUES (3,14);
INSERT INTO FILME_CINEMA (FILME_ID,CINEMA_ID) VALUES (4,14);
INSERT INTO FILME_CINEMA (FILME_ID,CINEMA_ID) VALUES (4,14);
INSERT INTO FILME_CINEMA (FILME_ID,CINEMA_ID) VALUES (6,14);

INSERT INTO FILME_CINEMA (FILME_ID,CINEMA_ID) VALUES (1,15);
INSERT INTO FILME_CINEMA (FILME_ID,CINEMA_ID) VALUES (2,15);
INSERT INTO FILME_CINEMA (FILME_ID,CINEMA_ID) VALUES (3,15);
INSERT INTO FILME_CINEMA (FILME_ID,CINEMA_ID) VALUES (4,15);
INSERT INTO FILME_CINEMA (FILME_ID,CINEMA_ID) VALUES (4,15);
INSERT INTO FILME_CINEMA (FILME_ID,CINEMA_ID) VALUES (6,15);


INSERT INTO CINEMA_HORARIO (CINEMA_ID,HORARIO_ID) VALUES (1,1);
INSERT INTO CINEMA_HORARIO (CINEMA_ID,HORARIO_ID) VALUES (1,2);
INSERT INTO CINEMA_HORARIO (CINEMA_ID,HORARIO_ID) VALUES (1,3);


INSERT INTO CINEMA_HORARIO (CINEMA_ID,HORARIO_ID) VALUES (2,1);
INSERT INTO CINEMA_HORARIO (CINEMA_ID,HORARIO_ID) VALUES (2,2);
INSERT INTO CINEMA_HORARIO (CINEMA_ID,HORARIO_ID) VALUES (2,3);


INSERT INTO CINEMA_HORARIO (CINEMA_ID,HORARIO_ID) VALUES (3,1);
INSERT INTO CINEMA_HORARIO (CINEMA_ID,HORARIO_ID) VALUES (3,2);
INSERT INTO CINEMA_HORARIO (CINEMA_ID,HORARIO_ID) VALUES (3,3);


INSERT INTO CINEMA_HORARIO (CINEMA_ID,HORARIO_ID) VALUES (4,1);
INSERT INTO CINEMA_HORARIO (CINEMA_ID,HORARIO_ID) VALUES (4,2);
INSERT INTO CINEMA_HORARIO (CINEMA_ID,HORARIO_ID) VALUES (4,3);


INSERT INTO CINEMA_HORARIO (CINEMA_ID,HORARIO_ID) VALUES (5,1);
INSERT INTO CINEMA_HORARIO (CINEMA_ID,HORARIO_ID) VALUES (5,2);
INSERT INTO CINEMA_HORARIO (CINEMA_ID,HORARIO_ID) VALUES (5,3);


INSERT INTO HORARIO_ACENTO (HORARIO_ID,ACENTO_ID) VALUES (1,1);
INSERT INTO HORARIO_ACENTO (HORARIO_ID,ACENTO_ID) VALUES (1,2);
INSERT INTO HORARIO_ACENTO (HORARIO_ID,ACENTO_ID) VALUES (1,3);
INSERT INTO HORARIO_ACENTO (HORARIO_ID,ACENTO_ID) VALUES (1,4);
INSERT INTO HORARIO_ACENTO (HORARIO_ID,ACENTO_ID) VALUES (1,5);
INSERT INTO HORARIO_ACENTO (HORARIO_ID,ACENTO_ID) VALUES (1,6);
INSERT INTO HORARIO_ACENTO (HORARIO_ID,ACENTO_ID) VALUES (1,7);
INSERT INTO HORARIO_ACENTO (HORARIO_ID,ACENTO_ID) VALUES (1,8);
INSERT INTO HORARIO_ACENTO (HORARIO_ID,ACENTO_ID) VALUES (1,9);
INSERT INTO HORARIO_ACENTO (HORARIO_ID,ACENTO_ID) VALUES (1,10);
INSERT INTO HORARIO_ACENTO (HORARIO_ID,ACENTO_ID) VALUES (1,11);
INSERT INTO HORARIO_ACENTO (HORARIO_ID,ACENTO_ID) VALUES (1,12);
INSERT INTO HORARIO_ACENTO (HORARIO_ID,ACENTO_ID) VALUES (1,13);
INSERT INTO HORARIO_ACENTO (HORARIO_ID,ACENTO_ID) VALUES (1,14);
INSERT INTO HORARIO_ACENTO (HORARIO_ID,ACENTO_ID) VALUES (1,15);
INSERT INTO HORARIO_ACENTO (HORARIO_ID,ACENTO_ID) VALUES (1,16);
INSERT INTO HORARIO_ACENTO (HORARIO_ID,ACENTO_ID) VALUES (1,17);
INSERT INTO HORARIO_ACENTO (HORARIO_ID,ACENTO_ID) VALUES (1,18);
INSERT INTO HORARIO_ACENTO (HORARIO_ID,ACENTO_ID) VALUES (1,19);
INSERT INTO HORARIO_ACENTO (HORARIO_ID,ACENTO_ID) VALUES (1,20);

INSERT INTO HORARIO_ACENTO (HORARIO_ID,ACENTO_ID) VALUES (2,1);
INSERT INTO HORARIO_ACENTO (HORARIO_ID,ACENTO_ID) VALUES (2,2);
INSERT INTO HORARIO_ACENTO (HORARIO_ID,ACENTO_ID) VALUES (2,3);
INSERT INTO HORARIO_ACENTO (HORARIO_ID,ACENTO_ID) VALUES (2,4);
INSERT INTO HORARIO_ACENTO (HORARIO_ID,ACENTO_ID) VALUES (2,5);
INSERT INTO HORARIO_ACENTO (HORARIO_ID,ACENTO_ID) VALUES (2,6);
INSERT INTO HORARIO_ACENTO (HORARIO_ID,ACENTO_ID) VALUES (2,7);
INSERT INTO HORARIO_ACENTO (HORARIO_ID,ACENTO_ID) VALUES (2,8);
INSERT INTO HORARIO_ACENTO (HORARIO_ID,ACENTO_ID) VALUES (2,9);
INSERT INTO HORARIO_ACENTO (HORARIO_ID,ACENTO_ID) VALUES (2,10);
INSERT INTO HORARIO_ACENTO (HORARIO_ID,ACENTO_ID) VALUES (2,11);
INSERT INTO HORARIO_ACENTO (HORARIO_ID,ACENTO_ID) VALUES (2,12);
INSERT INTO HORARIO_ACENTO (HORARIO_ID,ACENTO_ID) VALUES (2,13);
INSERT INTO HORARIO_ACENTO (HORARIO_ID,ACENTO_ID) VALUES (2,14);
INSERT INTO HORARIO_ACENTO (HORARIO_ID,ACENTO_ID) VALUES (2,15);
INSERT INTO HORARIO_ACENTO (HORARIO_ID,ACENTO_ID) VALUES (2,16);
INSERT INTO HORARIO_ACENTO (HORARIO_ID,ACENTO_ID) VALUES (2,17);
INSERT INTO HORARIO_ACENTO (HORARIO_ID,ACENTO_ID) VALUES (2,18);
INSERT INTO HORARIO_ACENTO (HORARIO_ID,ACENTO_ID) VALUES (2,19);
INSERT INTO HORARIO_ACENTO (HORARIO_ID,ACENTO_ID) VALUES (2,20);

INSERT INTO HORARIO_ACENTO (HORARIO_ID,ACENTO_ID) VALUES (3,1);
INSERT INTO HORARIO_ACENTO (HORARIO_ID,ACENTO_ID) VALUES (3,2);
INSERT INTO HORARIO_ACENTO (HORARIO_ID,ACENTO_ID) VALUES (3,3);
INSERT INTO HORARIO_ACENTO (HORARIO_ID,ACENTO_ID) VALUES (3,4);
INSERT INTO HORARIO_ACENTO (HORARIO_ID,ACENTO_ID) VALUES (3,5);
INSERT INTO HORARIO_ACENTO (HORARIO_ID,ACENTO_ID) VALUES (3,6);
INSERT INTO HORARIO_ACENTO (HORARIO_ID,ACENTO_ID) VALUES (3,7);
INSERT INTO HORARIO_ACENTO (HORARIO_ID,ACENTO_ID) VALUES (3,8);
INSERT INTO HORARIO_ACENTO (HORARIO_ID,ACENTO_ID) VALUES (3,9);
INSERT INTO HORARIO_ACENTO (HORARIO_ID,ACENTO_ID) VALUES (3,10);
INSERT INTO HORARIO_ACENTO (HORARIO_ID,ACENTO_ID) VALUES (3,11);
INSERT INTO HORARIO_ACENTO (HORARIO_ID,ACENTO_ID) VALUES (3,12);
INSERT INTO HORARIO_ACENTO (HORARIO_ID,ACENTO_ID) VALUES (3,13);
INSERT INTO HORARIO_ACENTO (HORARIO_ID,ACENTO_ID) VALUES (3,14);
INSERT INTO HORARIO_ACENTO (HORARIO_ID,ACENTO_ID) VALUES (3,15);
INSERT INTO HORARIO_ACENTO (HORARIO_ID,ACENTO_ID) VALUES (3,16);
INSERT INTO HORARIO_ACENTO (HORARIO_ID,ACENTO_ID) VALUES (3,17);
INSERT INTO HORARIO_ACENTO (HORARIO_ID,ACENTO_ID) VALUES (3,18);
INSERT INTO HORARIO_ACENTO (HORARIO_ID,ACENTO_ID) VALUES (3,19);
INSERT INTO HORARIO_ACENTO (HORARIO_ID,ACENTO_ID) VALUES (3,20);
